import { PALETTES } from './palettes';
import type { DashboardDataset, DashboardSpec } from './types';

export function mockedAiSpec(datasets: DashboardDataset[]): DashboardSpec {
  const ds = datasets[0]?.id || 'ds-sales';
  const palette = PALETTES.find((p) => p.id === 'ocean') || PALETTES[0];
  return {
    version: 1,
    id: 'mocked-ai',
    title: 'Northstar revenue operations',
    subtitle: 'Seasonality, discount pressure, and channel mix on 640 orders.',
    intent: 'Mocked catalog board for SSR review',
    archetype: 'command-center',
    seed: 404,
    theme: {
      palette: { ...palette, background: 'transparent' },
      fontFamily: 'font-sans',
      headingFont: 'font-grotesk',
      radius: 'rounded-2xl',
      density: 'comfortable',
    },
    narrative: {
      headline: 'Direct and enterprise still carry the book',
      body: 'Revenue, margin, and discount sit on the same board so a model-invented dip cannot hide.',
    },
    sections: [{ id: 'main', title: 'Primary' }],
    widgets: [
      {
        id: 'kpi-rev',
        type: 'kpi',
        title: 'Total revenue',
        layout: { x: 8, y: 0, w: 4, h: 3 },
        datasetId: ds,
        componentId: 'arc.metric-card',
        yField: 'revenue',
        kpi: { value: '', field: 'revenue', aggregation: 'sum', format: 'currency' },
      },
      {
        id: 'kpi-gm',
        type: 'kpi',
        title: 'Gross margin',
        layout: { x: 8, y: 3, w: 4, h: 3 },
        datasetId: ds,
        componentId: 'sbi.kpi-drilldown',
        yField: 'gross_margin',
        kpi: { value: '', field: 'gross_margin', aggregation: 'avg', format: 'percent' },
      },
      {
        id: 'trend',
        type: 'chart',
        title: 'Monthly revenue and units',
        layout: { x: 0, y: 0, w: 8, h: 6 },
        chartType: 'line',
        datasetId: ds,
        componentId: 'arc.line-chart',
        xField: 'order_date',
        yField: 'revenue',
        series: [
          { field: 'revenue', style: 'line' },
          { field: 'units', style: 'dashed' },
        ],
        compare: 'previous-period',
      },
      {
        id: 'region',
        type: 'chart',
        title: 'Revenue by region',
        layout: { x: 0, y: 6, w: 6, h: 6 },
        chartType: 'horizontal-bar',
        datasetId: ds,
        componentId: 'arc.bar-chart',
        xField: 'region',
        yField: 'revenue',
      },
      {
        id: 'multiples',
        type: 'chart',
        title: 'Revenue small multiples by channel',
        layout: { x: 6, y: 6, w: 6, h: 6 },
        chartType: 'area',
        datasetId: ds,
        componentId: 'sbi.small-multiples',
        xField: 'order_date',
        yField: 'revenue',
        groupField: 'channel',
      },
      {
        id: 'bullet',
        type: 'chart',
        title: 'Discount vs margin',
        layout: { x: 0, y: 12, w: 4, h: 5 },
        chartType: 'bar',
        datasetId: ds,
        componentId: 'sbi.bullet-variance',
        xField: 'region',
        yField: 'discount_rate',
        targetField: 'gross_margin',
      },
      {
        id: 'scatter',
        type: 'chart',
        title: 'Discount vs margin',
        layout: { x: 4, y: 12, w: 8, h: 5 },
        chartType: 'scatter',
        datasetId: ds,
        componentId: 'arc.bar-chart',
        xField: 'discount_rate',
        yField: 'gross_margin',
      },
      {
        id: 'table',
        type: 'table',
        title: 'Top 15 orders by revenue',
        layout: { x: 0, y: 17, w: 12, h: 6 },
        datasetId: ds,
        componentId: 'arc.sortable-data-table',
        columns: ['order_date', 'region', 'channel', 'product', 'segment', 'revenue'],
        table: {
          sort: { field: 'revenue', dir: 'desc' },
          limit: 15,
          measures: [{ field: 'revenue', agg: 'sum', format: 'currency' }],
        },
      },
    ],
  };
}
